# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

# SPA history fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Service worker should not be cached aggressively while still updatable
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

# Helpful caching for static assets (tweak to taste)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
