# netlify.toml
[build]
  command = "npm run build"
  publish = "dist"

# Single Page App rewrite: send all unknown paths to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# (Optional) Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# (Optional) Cache static assets emitted by Vite
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
